// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comment/get": {
            "get": {
                "description": "获取评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "获取评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "PID",
                        "name": "postid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/comment/post": {
            "post": {
                "description": "评论帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "评论帖子",
                "parameters": [
                    {
                        "description": "Comment",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commentservice.Comment"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "UID",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/comment/reply": {
            "post": {
                "description": "评论回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "评论回复",
                "parameters": [
                    {
                        "description": "Comment",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commentservice.Comment"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "UID",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "LoginForm",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountservice.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/create": {
            "post": {
                "description": "Create",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "创建帖子",
                "parameters": [
                    {
                        "description": "CreatePostForm",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postservice.CreatePostForm"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "UID",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/delete/{postid}": {
            "delete": {
                "description": "删除一个帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "DeleteByPostID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "postid",
                        "name": "postid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/edit/{postid}": {
            "put": {
                "description": "编辑一个帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "EditByPostID",
                "parameters": [
                    {
                        "description": "EditPostForm",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postservice.EditPostForm"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "postid",
                        "name": "postid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "UID",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/get/home": {
            "post": {
                "description": "GetWaths",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "获得该用户关注的用户所有的帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/getby/postid/{postid}": {
            "post": {
                "description": "GetByPostID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "GetByPostID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "postid",
                        "name": "postid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/getby/uid/{uid}": {
            "post": {
                "description": "GetByUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "获得该用户的所有帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/like": {
            "post": {
                "description": "LikePost",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "点赞一个帖子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ownerid",
                        "name": "ownerid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "owner_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/likedornot": {
            "post": {
                "description": "LikedOrNot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "点赞是否存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ownerid",
                        "name": "ownerid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "owner_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/post/undolike": {
            "delete": {
                "description": "UndoLike",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "取消点赞一个帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ownerid",
                        "name": "ownerid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "owner_type",
                        "name": "owner_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register/attempt": {
            "post": {
                "description": "验证注册表单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Attempt",
                "parameters": [
                    {
                        "description": "AttemptForm",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountservice.AttemptForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register/register": {
            "post": {
                "description": "注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "RegisterForm",
                        "name": "Form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountservice.RegisterForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register/sendmailcode": {
            "post": {
                "description": "发送邮件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "PostEmail",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/bewatchedornot": {
            "post": {
                "description": "BeWatchedOrNot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "是否关注",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/getby/uid/{uid}": {
            "post": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "GetByID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/getby/username/{username}": {
            "post": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "GetByUserName",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/getfans": {
            "post": {
                "description": "获取粉丝列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取粉丝列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/info": {
            "put": {
                "description": "编辑用户登录信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Info",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UID",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "description": "EditForm",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountservice.EditForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户登录信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "info",
                        "name": "info",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/photo": {
            "put": {
                "description": "获取更改头像",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Info",
                "parameters": [
                    {
                        "description": "PhotoFrom",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountservice.PhotoFrom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/unwatch/{uid}": {
            "post": {
                "description": "取关用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UnWatchUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/unwatchedusers": {
            "post": {
                "description": "没关注的用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "UnWatchedUsers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/watch/{uid}": {
            "post": {
                "description": "关注用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "WatchUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/watchedornot": {
            "post": {
                "description": "WatchedOrNot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "是否关注",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/watchedusers": {
            "post": {
                "description": "HadWatchedUsers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "已经关注的用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "accountservice.AttemptForm": {
            "type": "object",
            "required": [
                "emailorphone",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "emailorphone": {
                    "type": "string",
                    "example": "1652091948@qq.com"
                },
                "name": {
                    "type": "string",
                    "example": "志明"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "zzk"
                }
            }
        },
        "accountservice.EditForm": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "bio": {
                    "type": "string",
                    "example": "my bio"
                },
                "birth_day": {
                    "type": "string",
                    "example": "2022-12-12"
                },
                "gender": {
                    "type": "string",
                    "example": "mele"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "志明"
                },
                "website": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "accountservice.LoginForm": {
            "type": "object",
            "required": [
                "emailorphoneorusername",
                "password"
            ],
            "properties": {
                "emailorphoneorusername": {
                    "type": "string",
                    "example": "zzk"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "accountservice.PhotoFrom": {
            "type": "object",
            "properties": {
                "data_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/upload.DataList"
                    }
                }
            }
        },
        "accountservice.RegisterForm": {
            "type": "object",
            "required": [
                "emailorphone",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "birth_day": {
                    "type": "string",
                    "example": "2022-12-12"
                },
                "code": {
                    "type": "string",
                    "example": "1234"
                },
                "emailorphone": {
                    "type": "string",
                    "example": "1652091948@qq.com"
                },
                "name": {
                    "type": "string",
                    "example": "志明"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "zzk"
                }
            }
        },
        "commentservice.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "likesCounts": {
                    "type": "integer"
                },
                "postID": {
                    "type": "integer"
                },
                "replyID": {
                    "type": "integer"
                },
                "replys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/commentservice.Comment"
                    }
                },
                "replysCounts": {
                    "type": "integer"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "postservice.CreatePostForm": {
            "type": "object",
            "properties": {
                "categorys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "example",
                        "test"
                    ]
                },
                "mycomment": {
                    "type": "string",
                    "example": "我的评论"
                },
                "pictures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://pic.kiass.top/1660055054189wallhaven-rd2jw1_1920x1080.png",
                        "http://pic.kiass.top/1660055054194wallhaven-x8eydz.jpg"
                    ]
                },
                "place": {
                    "type": "string",
                    "example": "school"
                }
            }
        },
        "postservice.EditPostForm": {
            "type": "object",
            "properties": {
                "categorys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mycomment": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                }
            }
        },
        "upload.DataList": {
            "type": "object",
            "properties": {
                "base64Date": {
                    "type": "string"
                },
                "blob": {
                    "type": "string"
                },
                "blobData": {},
                "cropedBlobUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "percentage": {
                    "type": "integer"
                },
                "raw": {},
                "size": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1016",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Fake Ins API",
	Description:      "Fake Ins的API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
